name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ваші залежності

    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .  # Запускаємо flake8 для перевірки всіх файлів в репозиторії

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q  # Запускаємо тести, зупиняємось після 1 помилки, приховуємо попередження
